const sequelize = require("../../../config/sequelize");

const Job_Openings = sequelize.define(
  "job_openings",
  {
    // id: {
    //   type: "DataTypes.INTEGER",
    //   unique: false,
    //   allowNull: false,
    //   primaryKey: true,
    //   defaultValue: "nextval('terms.job_openings_id_seq'::regclass)",
    //   autoIncrement: false,
    // },
    currency: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    panal_member: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    job_type: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    dept_code: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    is_active: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: "true",
      autoIncrement: false,
    },
    job_title: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    created_at: {
      type: "DataTypes.DATE",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    created_by: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    candidate_owner: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    recruiters: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    hire_manager: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    updated_at: {
      type: "DataTypes.DATE",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    updated_by: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    job_location: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    can_emp_apply: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    openings_count: {
      type: "DataTypes.INTEGER",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    req_experience: {
      type: "DataTypes.FLOAT",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    screening_ques: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    can_apply_later: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    candidate_owner: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    is_job_priority: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    job_description: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    salary_range_to: {
      type: "DataTypes.INTEGER",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    target_hire_date: {
      type: "DataTypes.DATE",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    salary_range_from: {
      type: "DataTypes.INTEGER",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    job_portal_publish: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    career_site_publish: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    notify_mng_cand_add: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    notify_recr_cand_add: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    apply_later_after_type: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    apply_later_after_number: {
      type: "DataTypes.INTEGER",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    recr_access_to_candidate: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
    interview_feedback_visible: {
      type: "DataTypes.STRING",
      unique: false,
      allowNull: false,
      primaryKey: false,
      defaultValue: null,
      autoIncrement: false,
    },
    profile_access_interviewer: {
      type: "DataTypes.BOOLEAN",
      unique: false,
      allowNull: true,
      primaryKey: false,
      defaultValue: "false",
      autoIncrement: false,
    },
  },
  {
    tableName: "job_openings",
    timestamps: true,
    updatedAt: "updated_at",
    createdAt: "created_at",
  }
);

//Job_Openings.removeAttribute("id");
module.exports = Job_Openings;
