const sequelize = require("../../config/sequelize");
const Department = require("../Base/Department");
const Emp_Master_Hd = require("../Employee/EmpMasterHd");
// This Controller Use For TravelExpence
const TravelExpenseModal = sequelize.define(
    "travel_expense",
    {
        expense_type: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: false,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        category: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: false,
            autoIncrement: false,
        },
        project_center: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        title: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: false,
            autoIncrement: false,
        },
        expense_date: {
            type: "DataTypes.DATE",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        currency: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: false,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        amount: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: false,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        from_location: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        to_location: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        distance: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        expense_comment: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        exp_date: {
            type: "DataTypes.DATE",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        merchant: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },

        exp_cat: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        location: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        project: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        amt: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        purpose: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        invoice_number: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        hour: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        minute: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        comment: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        upload_reciept: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        curren: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        approve_date: {
            type: "DataTypes.DATE",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        approve_by: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        approve_status: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        emp_cd: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
        department: {
            type: "DataTypes.STRING",
            unique: false,
            allowNull: true,
            primaryKey: false,
            defaultValue: null,
            autoIncrement: false,
        },
    },
    {
        tableName: "travel_expense",
        timestamps: true,
        updatedAt: "updated_at",
        createdAt: "created_at",
    }
);
TravelExpenseModal.hasOne(Emp_Master_Hd, {
    foreignKey: "emp_number",
    sourceKey: "emp_cd",
    as: "EmpName",
});
TravelExpenseModal.hasOne(Department, {
    foreignKey: "code",
    sourceKey: "department",
    as: "DepartmentName",
});
module.exports = TravelExpenseModal;
