const sequelize = require("../../config/sequelize");

const Unit = sequelize.define(
  "unit",
  {
    city_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: true,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    sbu_code: {
      type: "DataTypes.INTEGER",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    name: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    address: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    operation_from: {
      type: "DataTypes.DATE",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    cst: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    short_name: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    cst_date: {
      type: "DataTypes.DATE",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    lst: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    pin: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    lst_date: {
      type: "DataTypes.DATE",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    telephone: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    fax: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: true,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    email: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: true,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    vmail: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    head: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    unit_desc: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    branch_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    tin: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    unit: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    range: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    division: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    divsion: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ecc_no: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    unit_indc: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_tax_regd_no: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_tax_regd_dt: {
      type: "DataTypes.DATE",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    assessee_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    type_of_org: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    major_ser_cat_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    credit_adj_per: {
      type: "DataTypes.FLOAT",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_division_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_range_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_comm_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_division_name: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_range_name: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_comm_name: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_focal_bank_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_focal_bank_name: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_focal_bank_add: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    properitor: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    pan_no: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    range1: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    commision: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    div_address: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    date_of_reg: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    pf_est_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    esi_est_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ser_tax_regd_no1: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    unit_curr: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    created_by: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    created_at: {
      type: "DataTypes.DATE",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    last_updated_by: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    updated_at: {
      type: "DataTypes.DATE",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    object_version_number: {
      type: "DataTypes.INTEGER",
      unique: false,
      primaryKey: false,
      allowNull: false,
      defaultValue: null,
      autoIncrement: false,
    },
    gst_reg_no: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    gst_reg_dt: {
      type: "DataTypes.DATE",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    cin: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    cin_no: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    unit_ho: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    unit_desc_for_exp: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    unit_add_for_exp: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    unit_city_for_exp: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    inv_ind: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    publickey: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    einvusername: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    einvpassword: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    client_id: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    client_secret: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    connection_string: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    rec_email_id: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    ewaybill_gst: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    eway_username: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    eway_password: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    eway_client_id: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    eway_client_secret: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    eway_client_username: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    eway_client_password: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    hr_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    profit_center_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    it_soft_unit_code: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    it_soft_table_name_ATND: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
    it_soft_table_name_emp: {
      type: "DataTypes.STRING",
      unique: false,
      primaryKey: false,
      allowNull: true,
      defaultValue: null,
      autoIncrement: false,
    },
  },
  {
    tableName: "unit",
    timestamps: true,
    updatedAt: "updated_at",
    createdAt: "created_at",
  }
);

Unit.removeAttribute("id");

module.exports = Unit;
